name: Evaluación RAG

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - '.github/workflows/eval.yml'
  workflow_dispatch:

jobs:
  run-eval:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar evaluación
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python app/run_eval.py
